# Base configuration for Gitleaks
# This file defines rules for detecting secrets and sensitive information

# Title of the configuration
title = "Neopilot.nvim Secret Scanning Configuration"

# Extend the default configuration
[[rules]]
  description = "Generic API Key"
  regex = '''(?i)(?:key|api|token|secret|password)[^\w\d][\w\d]*[=:][\s\"\']*([\w\d\-_=]+)[\s\"\']*'''
  tags = ["key", "api", "token", "secret", "password"]
  entropy = 3.5

[[rules]]
  description = "AWS Access Key ID"
  regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
  tags = ["aws", "key"]

[[rules]]
  description = "AWS Secret Access Key"
  regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
  tags = ["aws", "key"]

[[rules]]
  description = "GitHub Personal Access Token"
  regex = '''(ghp|gho|ghu|ghs|ghr)[a-zA-Z0-9]{36}'''
  tags = ["github", "token"]

[[rules]]
  description = "Slack Token"
  regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})?'''
  tags = ["slack", "token"]

[[rules]]
  description = "RSA private key"
  regex = '''-----BEGIN RSA PRIVATE KEY-----'''
  tags = ["key", "rsa"]

[[rules]]
  description = "SSH private key"
  regex = '''-----BEGIN (DSA|EC|OPENSSH) PRIVATE KEY-----'''
  tags = ["key", "ssh"]

# Allow list - paths to ignore
[allowlist]
  description = "Files to ignore in the scan"
  paths = [
    "**/*.md",
    "**/*.txt",
    "**/test/**",
    "**/tests/**",
    "**/node_modules/**",
    "**/vendor/**",
    "**/dist/**",
    "**/build/**",
    "**/*.min.js",
    "**/*.bundle.js",
    "**/package-lock.json",
    "**/yarn.lock"
  ]

  # Allow specific patterns in specific files
  commits = [
    "^initial commit$",
    "^bump version"
  ]

# Configure entropy settings
[allowlist.regexes]
  description = "Regex patterns to allow"
  regexes = [
    ".*example.*",
    ".*test.*",
    ".*mock.*",
    ".*sample.*",
    ".*placeholder.*",
    "[0-9a-f]{7}\s+\(.*\)$",  # Git commit hashes
    "[0-9a-f]{40}"             # Full git hashes
  ]
